name: Zombie
version: '${project.version}'
main: com.iseong.zombie.Zombie
api-version: '1.20'
author: 'inseong2010'
depend:
  - LuckPerms
softdepend:
  - Vault
  - VaultChatFormatter
commands:
  zombie:
    aliases: [z]