name: Zombie
version: '${project.version}'
main: kr.kro.iseong.zombie.Zombie
api-version: '1.20'
depend:
  - LuckPerms
softdepend:
  - Vault
  - VaultChatFormatter
commands:
  zombie:
    description: 플러그인을 조작할 수 있습니다.