name: Zombie
version: '${project.version}'
main: com.iseong.zombie.zombie
api-version: '1.20'
author: 'inseong2010'
depend:
  - LuckPerms
  - BanManager
softdepend:
  - Vault
  - VaultChatFormatter
commands:
  zombie:
    description: Zombie plugin startup command
  team:
    description: Zombie plugin team command
config:
  dataManager
  teamManager